[package]
name = "cao"
version = "0.1.0"
authors = ["Johann Lee <me@qinka.pro>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
clap      = "2.3"
ureq = { version = "2", features = ["json"] }
derive_more = "0.99.2"
serde_json = "1.0"
